name: mlenv
channels:
- defaults
dependencies:
 - python=3.6.3
 - numpy
 - scipy
 - pandas
 - matplotlib
 - seaborn
 - scikit-learn
 - scikit-image
 - tensorflow 
 - jupyter
 - requests
 - urllib3
 - beautifulsoup4
 - click
 - nose
 - flask
 - pip:
   - virtualenv
   - watermark
   - sexmachine
   - xgboost
